config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    resources :users do
      resources :tweets do
        resources :likes
        resources :friends
      end
    end
  end
  namespace :admin do
    resources :users do
      resources :likes
    end
  end
  namespace :admin do
    resources :tweets do
      resources :likes
    end
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :tweets do 
   
    post 'tweets', to: 'tweets#tweet'
    resources :likes
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  get 'api/news', to: 'tweets#news'
  get 'api(/:startdate)(/:enddate)', to: 'tweets#dates'
  resources :friends, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    belongs_to :source_tweet, optional: true, inverse_of: :tweets, class_name: 'Tweet', foreign_key: 'tweet_id'
    has_many :tweets, inverse_of: :source_tweet, class_name: 'Tweet', foreign_key: 'tweet_id', dependent: :destroy
    has_many :likes, dependent: :destroy

    #para ordenar la paginación
    default_scope {order("created_at DESC")}
    validates :content, length: {minimum: 2, message: 'Debes colocarle contenido al tweet mín 2 caracteres!'}
    validates :content, length: {maximum: 140, message: 'El máximo es de 140 caracteres!'}
    validates :content, presence: true, allow_blank: false
    
    #scope para ver mis propios tweets
    scope :my_tweets, -> (current_user) {where(user_id: current_user)}
    #scope :tweets_for_me, -> (current_user) {where(user_id: current_user).or(friend_id: current_user.friends)}
   
    def self.search(search)
        where("content LIKE ?", "%#{search}%")
    end



    def content
        if source_tweet
          source_tweet.content
        else
          super
        end
    end
      
    def content=(content)
        if source_tweet
          raise 'retweets cannot have content'
        else
          super
        end
    end
      
     
    validates :content, absence: true, if: :source_tweet
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :retweet]
  before_action :authenticate_user!, except: [:index, :news, :dates]
  # include ActionController::HttpAuthentication::Basic::ControllerMethods
  # http_basic_authenticate_with name: "apituit", password: "Tuits", only: :create 

  # GET /tweets
  # GET /tweets.json
  def index
    if params[:search]
      @tweets = Tweet.search(params[:search]).page(params[:page]).order("created_at DESC")
      
    else
      #@tweets = Tweet.tweets_for_me(current_user).page(params[:page])
      #@tweets = Tweet.where("user.name IN (?)", current_user.friend.user_id).page(params[:page])
      @tweets = Tweet.my_tweets(current_user).page(params[:page])
    end
  end
  def news
    @arr= []
    @hash = {}
    @tweets = Tweet.limit(50)
    @tweets.each do |tweet|
      @arr += ["id": tweet.id, "content": tweet.content, "user_id": tweet.user_id, "likes": tweet.likes.count, "retweets": tweet.retweet]
    end
    @tweets = @arr
    render json: @tweets
  end

  def dates
    @arr= []
    @hash = {}
    
    startdate = Date.parse(params[:startdate])
    enddate = (Date.parse(params[:enddate])) + 1
    @tweets = Tweet.all.where(created_at: startdate..enddate) 
  
    @tweets.each do |tweet|
       @arr += ["id": tweet.id, "content": tweet.content, "user_id": tweet.user_id, "likes": tweet.likes.count, "retweets": tweet.retweet]
    end
    @tweets = @arr
    #@tweets = Tweet.all.find_by "created_at < ?", "2020-10-07 00:00"
    render json: @tweets
  end
  
  
  # GET /tweets/1
  # GET /tweets/1.json
  def show
    if params[:search]
      redirect_to tweets_path, alert: 'Busca dentro de la página de inicio por favor!'
      @tweets = Tweet.search(params[:search]).page(params[:page]).order("created_at DESC")
    end
    # if !@friend.nil? 
    #   @users = User.all
    #   @user = User.friend.find(params[:id])
    #   current_user
    #   if @current_user
    #     @friend = Friend.where(user_id: @user.id, friend_id: @current_user.id).first
    #   end
    # end

  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
   
  end

  # GET /tweets/1/edit
  def edit
    if @tweet.user_id != current_user.id 
      redirect_to root_path, alert: 'No puedes editar este tweet!'
    end
  end

  # POST /tweets
  # POST /tweets.json
  def create

    @tweet = Tweet.new(tweet_params)
    if current_user != nil
      @tweet.user_id = current_user.id
    else 
      @tweet.user_id = params[:user_id]
    end 
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update

    @tweet = Tweet.find(params[:id])
        @tweet.update(like: !@tweet.like ) 
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end


def tweet
  original_tweet = Tweet.find_by(params[:id])
  @retweet = Tweet.new(
    user_id: current_user.id,
    tweet_id: original_tweet.id,
  )
  @retweet.save
  if @retweet.save
    redirect_to tweet_path, alert: 'Retweeted!'
  else
    redirect_to root_path, alert: 'Can not retweet'
  end
   
end


  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user, :like, :id, :tweet, :tweet_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_follow.html.erb
<%= form_for(current_user.active_friends.build) do |f| %>
  <div><%= hidden_field_tag :friend_id, @tweet.user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content, 'Escribe aquí tu tweet:' %> <br>
    <%= form.text_area :content %>
  </div>


  <div class="actions">
    <button type="submit" class="btn btn-primary btn-sm">Enviar</button>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="col-md-8">
    <h1>Editando...</h1> <br>

    <%= render 'form', tweet: @tweet %>
    <br>
    <%= link_to 'Show', @tweet %> |
    <%= link_to 'Back', tweets_path %><br>
</div>

app/views/tweets/index.html.erb
<div class="col-md-8">
  <% if !user_signed_in?%> 
    <h3> Crea una nueva cuenta o inicia sesión para ver Tweets! <i class="fa fa-twitter"> </i></h3>
  <% end  %>
  <% if user_signed_in?%>
    <%= form_with(model: @tweet=Tweet.new, local: true) do |form| %>
        
      
      <div class="row">
        <div class="form-group col-md-8 text-justify">
          
          <%= form.text_area :content, placeholder:'Escribe aquí tu tweet...' %>
        </div>


        <div class="actions col-md-8 ">
          <button type="submit" class="btn btn-primary btn-sm">Enviar</button>
        </div>
      </div>
    <% end %>
  <br>
  
  <br>
  <hr>

    <% @tweets.each do |tweet| %>
      <p><%= image_tag "#{tweet.user.picture}", style: 'height:45px; width:45px;'%>
         <%= tweet.user.name if tweet.user %>
      </p>
      <div class= "contenido ">
        <p>
            <%c = tweet.content%>
            <% d = " "%>
            <% arr = c.split(d)%> 
            <%arr.each do |arr|%>
              <% if arr.include?('#')%>
                <%= link_to "#{arr}", root_path(search:"#{arr}") %>
              <% else%>
                <%= print%><span><%=arr%></span>
              <%end%>
            <%end%>
        </p>
      </div>
        
        <h3> 
            <% pre_like = tweet.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= link_to raw('&#x1F495;'), tweet_like_path(tweet, pre_like), method: :delete %> 
              <% else %>
                <%= link_to raw('&#128128;'), tweet_likes_path(tweet), method: :post %>
              <% end %>
        <span><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? ' Like ' : ' Likes '%>
              <%= tweet.tweet_ids.count %>
              <%= link_to 'Retweet',  tweet_tweets_path(tweet.id), method: :post %></span>
        </h3>
        <p><%= link_to time_ago_in_words(tweet.created_at), tweet %>
        <% if user_signed_in? && tweet.user_id == current_user.id%>
          <%= link_to ' Editar', edit_tweet_path(tweet) %>
          <%= link_to ' Borrar', tweet, method: :delete, data: { confirm: 'Estás seguro?' } %></p>  
        <%end%>
      <hr>
    <% end %>

<br>

  
    
<%= link_to_next_page @tweets, 'Mostrar más tweets >>' %>

<br>
<%= link_to 'Nuevo Tweet', new_tweet_path %>
<br>
<%= link_to 'Inicio', root_path %>
<%end%> 
</div>

app/views/tweets/new.html.erb
<div class="col-md-8">
    <h1>¡Nuevo Tweet!</h1> <br>
    <%= render 'form', tweet: @tweet %> <br>
    <%= link_to 'Atrás', tweets_path %>
</div>

app/views/tweets/show.html.erb
<br>
<div class="col-md-8">
  <p>
    <strong> <%= link_to "#{@tweet.user.name}", user_path(@tweet.user.id) %></strong>
    <%=image_tag"#{@tweet.user.picture}", style: 'height:45px; width:45px;'%> <br>
  
  </p>
  <div class= "contenido ">
    <p>
    <%c = @tweet.content%>
    <%d = " "%>
    <%arr = c.split(d)%> 
    <%arr.each do |arr|%>
      <% if arr.include?('#')%>
        <%= link_to "#{arr}", root_path(search:"#{arr}") %>
      <% else%>
      <%= print%><span><%=arr%></span>
      <%end%>
    <%end%>
    </p>
  </div>
<div>
  <h2>
    <% pre_like = @tweet.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
    <%= link_to raw('&#128128;'), tweet_like_path(@tweet, pre_like), method: :delete %> 
    <% else %>
      <%= link_to raw('&#x1F495;'), tweet_likes_path(@tweet), method: :post %>
    <% end %>
  </h2>
</div>
  <p><%= @tweet.likes.count %> <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      <% @tweet.likes.each do |tweet| %>
        <tr>
            <td><%=image_tag"#{tweet.user.picture}", style: 'height:100px; width:100px;'%></td>
        </tr>
  <%end%>
<br>





<%= link_to 'Retweet'%>
<%# <p><%= link_to 'Retweet', tweets_path(@tweet.id), method: :post %> 
  
</p>
<br>
<p><%= time_ago_in_words(@tweet.created_at) %></p> <hr>




<% if @tweet.user == current_user %>
    <%= link_to 'Editar', edit_tweet_path(@tweet) %> <hr>
<%end%>
<%= link_to 'Atrás', tweets_path %>
</div>