config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    resources :users do
      resources :tweets do
        resources :likes
        resources :friends
      end
    end
  end
  namespace :admin do
    resources :users do
      resources :likes
    end
  end
  namespace :admin do
    resources :tweets do
      resources :likes
    end
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :tweets do 
   
    post 'tweets', to: 'tweets#tweet'
    resources :likes
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  get 'api/news', to: 'tweets#news'
  get 'api(/:startdate)(/:enddate)', to: 'tweets#dates'
  resources :friends, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top  navbar-dark bg-info">
      <h1 class="navbar-brand text-white"><i class="fa fa-twitter"> </i> Twitter </h1>
      <form class="form-inline">
        <%= form_tag(tweets_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar tweets" %>
        <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
        <% end %>
      </form>
    </nav>
      <br>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <br>
      <% if user_signed_in? %>
      <div class="row">
        <aside class="col-md-4 ">
          <section class="user">
            <h3 class= "text-bold">Bienvenido <%= current_user.name%>!</h3><br>
            <%=image_tag"#{current_user.picture}", style: 'height:150px; width:150px;'%><br>
            <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
          </section>
        </aside>
        <hr>
        <br>
      <% else %>
        <%= link_to 'Crear cuenta', new_user_registration_path %> | 
        <%= link_to 'Iniciar sesión', new_user_session_path%>
        <br>
      <%end%>
      <br>
      <%= yield %>

    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>